/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as BookingWaitingRouteImport } from './routes/booking-waiting'
import { Route as BookingRecapRouteImport } from './routes/booking-recap'
import { Route as BookingConfirmRouteImport } from './routes/booking-confirm'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingWaitingRoute = BookingWaitingRouteImport.update({
  id: '/booking-waiting',
  path: '/booking-waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRecapRoute = BookingRecapRouteImport.update({
  id: '/booking-recap',
  path: '/booking-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmRoute = BookingConfirmRouteImport.update({
  id: '/booking-confirm',
  path: '/booking-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-confirm': typeof BookingConfirmRoute
  '/booking-recap': typeof BookingRecapRoute
  '/booking-waiting': typeof BookingWaitingRoute
  '/circle': typeof CircleRoute
  '/health': typeof HealthRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-confirm': typeof BookingConfirmRoute
  '/booking-recap': typeof BookingRecapRoute
  '/booking-waiting': typeof BookingWaitingRoute
  '/circle': typeof CircleRoute
  '/health': typeof HealthRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-confirm': typeof BookingConfirmRoute
  '/booking-recap': typeof BookingRecapRoute
  '/booking-waiting': typeof BookingWaitingRoute
  '/circle': typeof CircleRoute
  '/health': typeof HealthRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-confirm'
    | '/booking-recap'
    | '/booking-waiting'
    | '/circle'
    | '/health'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-confirm'
    | '/booking-recap'
    | '/booking-waiting'
    | '/circle'
    | '/health'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/booking-confirm'
    | '/booking-recap'
    | '/booking-waiting'
    | '/circle'
    | '/health'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingConfirmRoute: typeof BookingConfirmRoute
  BookingRecapRoute: typeof BookingRecapRoute
  BookingWaitingRoute: typeof BookingWaitingRoute
  CircleRoute: typeof CircleRoute
  HealthRoute: typeof HealthRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-waiting': {
      id: '/booking-waiting'
      path: '/booking-waiting'
      fullPath: '/booking-waiting'
      preLoaderRoute: typeof BookingWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-recap': {
      id: '/booking-recap'
      path: '/booking-recap'
      fullPath: '/booking-recap'
      preLoaderRoute: typeof BookingRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirm': {
      id: '/booking-confirm'
      path: '/booking-confirm'
      fullPath: '/booking-confirm'
      preLoaderRoute: typeof BookingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingConfirmRoute: BookingConfirmRoute,
  BookingRecapRoute: BookingRecapRoute,
  BookingWaitingRoute: BookingWaitingRoute,
  CircleRoute: CircleRoute,
  HealthRoute: HealthRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
